sonar.projectKey=Venkat2525_spring-mvc-app
sonar.organization=venkat2525

sonar.sources=.
sonar.java.binaries=target/classes

sonar.exclusions=**/*.sh,**/*.bash

sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.libraries=target/dependency/*.jar