general:
  buildTool: maven

stages:
  Build:
    mavenExecuteStaticCodeChecks: true

  Compliance:
    sonarExecuteScan: true

steps:
  mavenExecute:
    goals: "clean install"

  sonarExecuteScan:
    dockerOptions: "-u 0"
    sonarProperties:
      sonar.java.binaries: "target/classes"