general:
  buildTool: maven

stages:
  Build:
    mavenExecuteStaticCodeChecks: false

steps:
  mavenExecute:
    goals: "clean install"

  sonarExecuteScan:
    serverUrl: "https://sonarcloud.io"
    organization: "venkat2525"
    projectKey: "Venkat2525_spring-mvc-app"
    additionalProperties:
      sonar.sources: "src/main/java"
      sonar.exclusions: "**/*.sh,**/*.yaml,**/*.yml,**/piper/**"
      sonar.java.binaries: "target/classes"

  cloudFoundryDeploy:
    cfApiEndpoint: "https://api.cf.ap21.hana.ondemand.com"
    cfOrg: "d38f4a1dtrial"
    cfSpace: "dev"
    cfAppName: "spring-mvc-app"
    deployType: "standard"