general:
  buildTool: maven

stages:
  Build:
    mavenExecuteStaticCodeChecks: false

  Additional Unit Tests:
    run: true

  Malware Scan:
    run: true

  Acceptance:
    run: true

  Compliance:
    run: true

  Release:
    run: true

steps:

  # 🔹 Build → Unit Tests
  mavenExecute:
    goals: "clean verify -Dtest=!*IT"

  # 🔹 Additional → Integration Tests
  additionalUnitTests:
    command: "mvn verify -Dit.test=*IT"

  # 🔹 Acceptance → simple test example
  acceptance:
    command: "echo Running acceptance tests"

  # 🔹 Release → dummy example
  release:
    command: "echo Releasing build"

  # 🔹 Deploy
  cloudFoundryDeploy:
    cfApiEndpoint: "https://api.cf.ap21.hana.ondemand.com"
    cfOrg: "d38f4a1dtrial"
    cfSpace: "dev"
    cfAppName: "spring-mvc-app"
    deployType: "standard"